name: simple_dart_starter_multilang
description: preconfigured application main window with navigation, path_bar, theme and language selection
version: 0.0.2
repository: https://github.com/simple-dart/simple_dart_starter_multilang
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_label: ^0.0.1
  simple_dart_modal_controller: ^0.0.1
  simple_dart_multilang_checkbox: ^0.0.2
  simple_dart_multilang_controller: ^0.0.1
  simple_dart_multilang_label: ^0.0.1
  simple_dart_multilang_link: ^0.0.1
  simple_dart_multilang_select_field: ^0.0.1
  simple_dart_select_field: ^0.0.1
  simple_dart_theme_controller: ^0.0.1
  simple_dart_ui_core: ^0.0.2
  simple_dart_view_controller: ^0.0.1
